// ============================================================
// CleanTrack — Sistema de idiomas (español / inglés)
// ------------------------------------------------------------
// - Detecta el idioma del dispositivo (o la preferencia guardada).
// - Permite cambiar manualmente con I18N.toggle().
// - Todas las traducciones viven aquí, en un solo lugar.
// ============================================================
(function () {
  var DICT = {
    es: {
      // Comunes (se repiten en varias pantallas)
      "comun.salir": "Salir",
      "comun.inicio": "← Inicio",
      "comun.verificando": "Verificando sesión...",
      "comun.sin_conexion": "Sin conexión a la base de datos.",

      // Pantalla de inicio
      "inicio.hola": "Hola",
      "inicio.subtitulo": "Centro de control del supervisor",
      "inicio.disponible": "Disponible",
      "inicio.kpi.limpiezas": "Limpiezas hoy",
      "inicio.kpi.incidencias": "Incidencias abiertas",
      "inicio.kpi.empleados": "Empleados activos",
      "inicio.kpi.edificios": "Edificios",
      "inicio.admin": "Admin",
      "inicio.registros.t": "Registros",
      "inicio.registros.d": "Ver áreas limpiadas, fotos y horarios en tiempo real",
      "inicio.empleados.t": "Empleados",
      "inicio.empleados.d": "Agregar, activar o desactivar al personal de limpieza",
      "inicio.edificios.t": "Edificios y áreas",
      "inicio.edificios.d": "Gestionar espacios y generar códigos QR por área",
      "inicio.incidencias.t": "Incidencias",
      "inicio.incidencias.d": "Reportes de insumos faltantes y problemas en cada edificio",
      "inicio.estadisticas.t": "Estadísticas",
      "inicio.estadisticas.d": "Cumplimiento, áreas más atendidas y tendencias",
      "inicio.reportes.t": "Reportes",
      "inicio.reportes.d": "Informe mensual en PDF para presentar al cliente",
      "inicio.soporte.t": "Soporte técnico",
      "inicio.soporte.d": "Contacto y ayuda con el uso de la plataforma",
      "inicio.administracion.t": "Administración",
      "inicio.administracion.d": "Suscripción, equipo y resumen de tu empresa",

      // Registros (dashboard)
      "reg.titulo": "Registros de limpieza",
      "reg.tiempo_real": "En tiempo real",
      "reg.actualizar": "Actualizar",
      "reg.m_hoy": "Registros hoy",
      "reg.m_foto": "Con foto",
      "reg.m_total": "Total histórico",
      "reg.edificio": "Edificio",
      "reg.todos_edificios": "Todos los edificios",
      "reg.sin_datos": "No hay datos aún",
      "reg.cargando": "Cargando registros...",
      "reg.vacio_edificio": "Aún no hay registros en este edificio.",
      "reg.vacio_todos": "Aún no hay registros. Cuando un empleado registre un área, aparecerá aquí.",
      "reg.con_foto": "Con foto",
      "reg.registrado": "Registrado",
      "reg.hoy": "Hoy",
      "reg.ayer": "Ayer",

      // Incidencias
      "inc.titulo": "Incidencias",
      "inc.subtitulo": "Insumos faltantes y problemas reportados",
      "inc.pendientes": "Pendientes",
      "inc.resueltas": "Resueltas",
      "inc.total": "Total",
      "inc.f_pendientes": "Pendientes",
      "inc.f_resueltas": "Resueltas",
      "inc.f_todas": "Todas",
      "inc.cargando": "Cargando incidencias...",
      "inc.vacio_pend": "No hay incidencias pendientes. ¡Todo en orden!",
      "inc.vacio_resueltas": "Aún no hay incidencias resueltas.",
      "inc.vacio_todas": "No hay incidencias.",
      "inc.tipo_insumo": "Falta insumo",
      "inc.tipo_problema": "Problema",
      "inc.estado_resuelta": "Resuelta",
      "inc.estado_pendiente": "Pendiente",
      "inc.btn_resolver": "Marcar como resuelta",
      "inc.btn_reabrir": "Reabrir",
      "inc.error_actualizar": "No se pudo actualizar: ",

      // Estadísticas
      "est.titulo": "Estadísticas",
      "est.subtitulo": "Rendimiento y tendencias por edificio",
      "est.cargando": "Cargando estadísticas...",
      "est.sin_datos": "No hay datos aún",
      "est.vacio": "Aún no hay registros. Cuando los empleados registren áreas, sus estadísticas aparecerán aquí agrupadas por edificio.",
      "est.de_edificio": "Estadísticas de este edificio",
      "est.m_total": "Total registros",
      "est.m_hoy": "Hoy",
      "est.m_semana": "Esta semana",
      "est.m_foto": "% con foto",
      "est.g_dias": "Actividad últimos 7 días",
      "est.g_areas": "Áreas más atendidas",
      "est.g_emp": "Actividad por empleado",
      "est.otras": "Otras",

      // Soporte
      "sop.titulo": "Centro de ayuda",
      "sop.subtitulo": "Preguntas frecuentes y contacto con soporte",
      "sop.buscar": "Escribe tu duda...",
      "sop.faq_label": "Preguntas frecuentes",
      "sop.sin_resultados": "No encontramos una respuesta para eso. Envíanos tu pregunta abajo y te ayudaremos.",
      "sop.form_titulo": "¿No encontraste tu respuesta?",
      "sop.form_sub": "Envíanos tu pregunta y la revisaremos",
      "sop.form_ph": "Escribe tu pregunta aquí...",
      "sop.enviar": "Enviar pregunta",
      "sop.escribe": "Escribe tu pregunta.",
      "sop.enviando": "Enviando...",
      "sop.error": "Error al enviar: ",
      "sop.ok": "✓ Tu pregunta fue enviada. Te responderemos pronto.",

      // Panel de administración
      "pan.sin_acceso": "Esta sección es solo para el administrador de la empresa.",
      "pan.volver": "← Volver al inicio",
      "pan.titulo": "Panel de administración",
      "pan.subtitulo": "Suscripción, resumen y equipo de tu empresa",
      "pan.sub_titulo": "Tu suscripción",
      "pan.sub_cargando": "Cargando...",
      "pan.sub_error": "No se pudo cargar la suscripción.",
      "pan.f_empresa": "Empresa",
      "pan.f_estado": "Estado",
      "pan.f_inicio": "Inicio de prueba",
      "pan.f_fin": "Fin de prueba",
      "pan.f_edificios": "Edificios contratados",
      "pan.f_precio": "Precio mensual",
      "pan.est_activa": "Activa",
      "pan.est_prueba": "En prueba gratis",
      "pan.est_suspendida": "Suspendida",
      "pan.resumen_titulo": "Resumen de tu empresa",
      "pan.r_edificios": "Edificios",
      "pan.r_empleados": "Empleados",
      "pan.r_registros": "Registros del mes",
      "pan.equipo_titulo": "Tu equipo de supervisores",
      "pan.equipo_cargando": "Cargando...",
      "pan.equipo_vacio": "No hay supervisores registrados.",
      "pan.nota": "Para agregar o quitar supervisores, contacta a soporte técnico por ahora. Pronto podrás gestionarlos directamente desde aquí.",
      "pan.rol_admin": "Administrador",
      "pan.rol_supervisor": "Supervisor",

      // Empleados (admin)
      "emp.titulo": "Empleados",
      "emp.subtitulo": "Gestiona el personal de limpieza y sus PIN",
      "emp.ver_registros": "Ver registros",
      "emp.agregar_titulo": "Agregar empleado",
      "emp.nombre": "Nombre completo",
      "emp.nombre_ph": "Ej. Ana Torres",
      "emp.pin": "PIN (4 dígitos)",
      "emp.pin_ph": "Ej. 4892",
      "emp.generar": "Generar",
      "emp.edificios": "Edificios donde trabaja",
      "emp.buscar_edificio": "Buscar y agregar edificio...",
      "emp.btn_agregar": "Agregar empleado",
      "emp.lista_titulo": "Empleados",
      "emp.buscar": "Buscar por nombre o edificio...",
      "emp.f_todos": "Todos",
      "emp.f_activos": "Activos",
      "emp.f_inactivos": "Inactivos",
      "emp.cargando": "Cargando...",
      "emp.editar_titulo": "Editar empleado",
      "emp.cancelar": "Cancelar",
      "emp.guardar": "Guardar cambios",
      "emp.sin_edificios": "Sin edificios asignados",
      "emp.vacio": "No se encontraron empleados.",
      "emp.pin_label": "PIN: ",
      "emp.vacio_inicial": "Aún no hay empleados. Agrega el primero arriba.",
      "emp.sin_coincidencias": "Sin coincidencias.",
      "emp.sin_edificio_asignado": "Sin edificio asignado",
      "emp.todos_agregados": "Ya agregaste todos los edificios.",

      "area.titulo": "Edificios y áreas",
      "area.subtitulo": "Gestiona espacios y genera códigos QR por área",
      "area.crear_edificio": "Crear edificio",
      "area.crear_area": "Crear área",
      "area.lista_titulo": "Edificios y sus áreas",
      "area.lista_sub": "Cada edificio con sus áreas. Toca \"Generar código QR\" para descargar el QR de cada área.",
      "area.cargando": "Cargando...",
      "area.m_edificio_titulo": "Crear edificio",
      "area.m_editar_titulo": "Editar edificio",
      "area.f_nombre_ed": "Nombre del edificio *",
      "area.f_direccion": "Dirección",
      "area.f_contacto": "Persona de contacto",
      "area.f_telefono": "Teléfono",
      "area.f_email": "Email",
      "area.f_pisos": "Número de pisos",
      "area.f_notas": "Notas",
      "area.guardar_ed": "Guardar edificio",
      "area.guardar_cambios": "Guardar cambios",
      "area.cancelar": "Cancelar",
      "area.m_area_titulo": "Crear área",
      "area.f_nombre_area": "Nombre del área *",
      "area.f_edificio": "Edificio *",
      "area.f_requiere_foto": "Requiere foto al registrar",
      "area.crear_area_btn": "Crear área",
      "area.qr_imprimir": "Imprimir tarjeta",
      "area.qr_cerrar": "Cerrar",
      "area.req_nombre_ed": "El nombre del edificio es obligatorio.",
      "area.guardando": "Guardando...",
      "area.sin_areas": "Sin áreas todavía.",
      "area.areas_count": "área(s)",
      "area.generar_qr": "Generar código QR",
      "area.req_nombre_area": "Escribe el nombre del área.",
      "area.area_sing": "área",
      "area.area_plu": "áreas",
      "area.activa_sing": "activa",
      "area.activa_plu": "activas",
      "area.requiere_foto_txt": "Requiere foto · ",
      "area.activa": "Activa",
      "area.inactiva": "Inactiva",
      "area.sin_areas_msg": "Este edificio aún no tiene áreas. Usa \"Crear área\" para agregar la primera.",
      "area.qr_title": "Código QR de esta área",

      "rep.titulo": "Reportes",
      "rep.generar_titulo": "Generar informe",
      "rep.generar_sub": "Crea un informe en PDF para presentar a tu cliente",
      "rep.edificio": "Edificio",
      "rep.tipo": "Tipo de informe",
      "rep.tipo_diario": "Diario (un día)",
      "rep.tipo_semanal": "Semanal (últimos 7 días)",
      "rep.tipo_mes_actual": "Mensual (este mes)",
      "rep.tipo_mes_pasado": "Mensual (mes pasado)",
      "rep.dia_informe": "Día del informe",
      "rep.btn_generar": "Generar PDF",
      "rep.preview_titulo": "Vista previa del informe",
      "rep.pv_areas": "Áreas limpiadas",
      "rep.pv_foto": "Con foto",
      "rep.pv_dias": "Días activos",
      "rep.pv_inc": "Incidencias",
      "rep.cargando_lista": "Cargando...",
      "rep.sin_datos": "No hay datos aún",
      "rep.generando": "Generando PDF...",
      "rep.listo": "✓ PDF generado y descargado.",
      "rep.error": "Error al generar: ",
      "rep.sel_edificio": "Selecciona un edificio.",
      "pdf.sub_diario": "Informe diario de limpieza",
      "pdf.sub_semanal": "Informe semanal de limpieza",
      "pdf.sub_mensual": "Informe mensual de limpieza",
      "pdf.periodo": "Período: ",
      "pdf.generado": "Generado: ",
      "pdf.pie": "Informe generado por CleanTrack",
      "pdf.t_areas_limpiadas": "Áreas limpiadas",
      "pdf.t_con_foto": "Con foto",
      "pdf.t_empleados": "Empleados",
      "pdf.t_incidencias": "Incidencias",
      "pdf.t_limpiezas": "Limpiezas",
      "pdf.t_dias_trab": "Días trabajados",
      "pdf.t_areas_cub": "Áreas cubiertas",
      "pdf.t_limpiezas_real": "Limpiezas realizadas",
      "pdf.t_inc_resueltas": "Incid. resueltas",
      "pdf.s_detalle": "Detalle de limpiezas",
      "pdf.s_inc_reportadas": "Incidencias reportadas",
      "pdf.s_act_dia": "Actividad por día",
      "pdf.s_inc_semana": "Incidencias de la semana",
      "pdf.s_act_semana": "Actividad por semana",
      "pdf.s_areas_atendidas": "Áreas más atendidas",
      "pdf.s_inc_mes": "Incidencias del mes",
      "pdf.vacio_limpiezas": "No se registraron limpiezas en este período.",
      "pdf.vacio_inc_periodo": "No se reportaron incidencias en este período.",
      "pdf.vacio_inc_semana": "No se reportaron incidencias esta semana.",
      "pdf.vacio_inc_mes": "No se reportaron incidencias este mes.",
      "pdf.ultimos7": "últimos 7 días",
      "pdf.de": " de ",
      "pdf.meses": "enero,febrero,marzo,abril,mayo,junio,julio,agosto,septiembre,octubre,noviembre,diciembre",

      "epl.cargando_area": "Cargando área...",
      "epl.label_pin": "Ingresa tu PIN para registrar",
      "epl.verificando": "Verificando...",
      "epl.borrar": "Borrar",
      "epl.hola": "Hola",
      "epl.tomar_foto": "Tomar foto del área",
      "epl.confirmar": "Confirmar área limpiada",
      "epl.registrar_con_foto": "Registrar área con esta foto",
      "epl.reportar_inc": "Reportar una incidencia",
      "epl.exito_titulo": "Área registrada",
      "epl.exito_nota": "Escanea el código de la siguiente área cuando termines de limpiarla.",
      "epl.inc_titulo": "Reportar incidencia",
      "epl.inc_insumo": "Falta un insumo",
      "epl.inc_problema": "Hay un problema",
      "epl.inc_desc_label": "Descripción",
      "epl.inc_desc_ph": "Ej. Se acabó el jabón en el dispensador / El inodoro está tapado",
      "epl.inc_agregar_foto": "Agregar foto (opcional)",
      "epl.inc_cambiar_foto": "Cambiar foto",
      "epl.inc_enviar": "Enviar reporte",
      "epl.cancelar": "Cancelar",
      "epl.area_no_esp": "Área no especificada",
      "epl.escanea_valido": "Escanea un código QR válido",
      "epl.area_no_enc": "Área no encontrada",
      "epl.verifica_qr": "Verifica el código QR",
      "epl.sin_conexion": "Sin conexión a la base de datos.",
      "epl.error_subir": "Error al subir foto: ",
      "epl.guardando": "Guardando registro...",
      "epl.no_guardar": "No se pudo guardar: ",
      "epl.error": "Error: ",
      "epl.inc_elige_tipo": "Elige el tipo: falta de insumo o problema.",
      "epl.inc_describe": "Describe la incidencia.",
      "epl.inc_subiendo": "Subiendo foto...",
      "epl.inc_enviando": "Enviando reporte...",
      "epl.inc_no_enviar": "No se pudo enviar: ",
      "epl.inc_ok": "✓ Reporte enviado. ¡Gracias!",
      "epl.pin_incorrecto": "PIN incorrecto. Intenta de nuevo.",
      "epl.sin_conexion_corta": "Sin conexión",
      "epl.demasiados": "Demasiados intentos. Espera un momento.",
      "epl.error_verificar": "Error al verificar. Intenta de nuevo.",
      "epl.pin_no_valido": "PIN no válido",

      "log.titulo": "Panel del supervisor",
      "log.subtitulo": "Gestión profesional de limpieza",
      "log.email": "Correo electrónico",
      "log.email_ph": "tucorreo@empresa.com",
      "log.password": "Contraseña",
      "log.entrar": "Iniciar sesión",
      "log.pie": "CleanTrack · Acceso seguro",
      "log.falta": "Escribe tu correo y contraseña.",
      "log.sin_conexion": "Sin conexión a la base de datos.",
      "log.verificando": "Verificando...",
      "log.incorrectos": "Correo o contraseña incorrectos.",

      "land.titulo_pagina": "CleanTrack — Demuestra cada limpieza que hace tu equipo",
      "land.nav_how": "Cómo funciona",
      "land.nav_why": "Por qué CleanTrack",
      "land.nav_quote": "Pide una cotización",
      "land.nav_login": "Acceso supervisor",
      "land.hero_h1": "Demuestra la gran limpieza<br>que entrega tu <span class=\"acento\">equipo</span>",
      "land.hero_sub": "La plataforma que convierte cada limpieza en evidencia que tus clientes pueden ver.",
      "land.hero_cta1": "Contáctanos para una cotización",
      "land.hero_cta2": "Mira cómo funciona",
      "land.prob_eyebrow": "⚠ El problema",
      "land.prob_h2": "Hacer un gran trabajo no basta.<br>Hay que <span class=\"rojo\">demostrarlo</span>.",
      "land.prob_intro": "Las empresas de limpieza no pierden contratos por trabajar mal — los pierden por no tener cómo demostrar que el trabajo se hizo.",
      "land.prob1_h": "\"¿Seguro que se limpió hoy?\"",
      "land.prob1_p": "El administrador del edificio tiene dudas, y sin pruebas, tu palabra no siempre basta para tranquilizarlo.",
      "land.prob2_h": "Quejas sin respaldo",
      "land.prob2_p": "Cuando llega un reclamo, no tienes registro de qué se hizo, cuándo, ni quién lo hizo.",
      "land.prob3_h": "Contratos que no se renuevan",
      "land.prob3_p": "Sin evidencia del valor que entregas, es difícil justificar la continuidad del servicio.",
      "land.prob_banner": "¿Y si cada limpieza quedara registrada <span class=\"hl\">automáticamente, con la hora exacta</span> — y pudieras exigir una foto en las áreas que elijas, como el <span class=\"hl\">lobby</span> o el <span class=\"hl\">salón</span>?",
      "land.sol_eyebrow": "✓ La solución",
      "land.sol_h2": "Todo queda registrado.<br>Lo ves <span class=\"verde\">en tiempo real</span>.",
      "land.sol_intro": "Cada área limpiada y cada incidencia aparecen al instante en tu panel y el de tus supervisores, con todo el detalle que necesitas.",
      "land.sol1_h": "Actividad de un vistazo",
      "land.sol1_p": "En cuanto un empleado registra un área, aparece en tu panel con quién la limpió, a qué hora y dónde — con evidencia fotográfica donde tú decidas.",
      "land.sol2_h": "Incidencias con todo el detalle",
      "land.sol2_p": "Si se acaba un insumo o algo se daña, tu equipo lo reporta en el momento. Recibes la alerta con el área, la descripción y una foto, para resolverlo rápido.",
      "land.sol3_h": "Reportes para tu cliente",
      "land.sol3_p": "Genera un reporte de cualquier día, semana o mes y envíaselo al administrador. Profesional, respaldado con evidencia, listo en segundos.",
      "land.sol4_h": "Foto donde tú decidas",
      "land.sol4_p": "Exige evidencia fotográfica solo en las áreas críticas — sin frenar a tu equipo en todo lo demás.",
      "land.how_eyebrow": "⚡ Cómo funciona",
      "land.how_h2": "Cuatro pasos. <span class=\"verde\">Cero complicaciones</span>.",
      "land.how_intro": "Tan simple que tu equipo lo usa desde el primer día — sin necesidad de capacitación.",
      "land.how1_h": "Escanea el QR del área",
      "land.how1_p": "Cada área tiene su propio código QR. El empleado llega y lo escanea con su celular. Sin app que instalar.",
      "land.how2_h": "Ingresa su PIN",
      "land.how2_p": "Cada empleado tiene un PIN personal de 4 dígitos. Lo ingresa y el sistema sabe quién hizo la limpieza — sin inicios de sesión complicados.",
      "land.how3_h": "Registra la limpieza",
      "land.how3_p": "El registro se guarda con la hora exacta y el nombre del empleado. Puedes exigir una foto en las áreas que elijas.",
      "land.how4_h": "Supervisa en tiempo real",
      "land.how4_p": "Tú y tus supervisores ven toda la actividad desde el panel, al instante. Sin llamadas, sin esperar reportes.",
      "land.video_h": "Míralo en acción",
      "land.video_sub": "Un vistazo rápido a cómo funciona CleanTrack, desde escanear el QR hasta tu panel en vivo.",
      "land.video_fallback": "Tu navegador no soporta el video.",
      "land.why_eyebrow": "✓ Por qué CleanTrack",
      "land.why_h2": "La diferencia está en la <span class=\"verde\">simplicidad</span>.",
      "land.why_intro": "Otras plataformas son complejas, caras y solo en inglés. CleanTrack hace lo que importa, bien y fácil.",
      "land.tab_th_ct": "CleanTrack",
      "land.tab_th_otros": "Otros",
      "land.tab_r1": "Facilidad de uso",
      "land.tab_r1_ct": "Sin capacitación",
      "land.tab_r1_o": "Curva de aprendizaje",
      "land.tab_r2": "Idioma",
      "land.tab_r2_ct": "Español e inglés",
      "land.tab_r2_o": "Solo inglés",
      "land.tab_r3": "Evidencia fotográfica",
      "land.tab_r3_ct": "Configurable por área",
      "land.tab_r3_o": "Limitada o aparte",
      "land.tab_r4": "Reportes al cliente",
      "land.tab_r4_ct": "Profesionales",
      "land.tab_r4_o": "Básicos",
      "land.tab_r5": "Precio mensual",
      "land.tab_r5_ct": "Accesible",
      "land.tab_r5_o": "Alto",
      "land.cta_h2": "Empieza a demostrar<br>tu valor <span class=\"acento\">hoy</span>",
      "land.cta_sub": "Tus primeros 30 días son gratis. Te ayudamos a configurar todo — sin costo, sin compromiso.",
      "land.cta_btn": "Contáctanos para una cotización",
      "land.foot_frase": "Cada limpieza, verificada.",
      "land.foot_login": "Acceso supervisor"
    },
    en: {
      "comun.salir": "Log out",
      "comun.inicio": "← Home",
      "comun.verificando": "Checking session...",
      "comun.sin_conexion": "No connection to the database.",

      "inicio.hola": "Hi",
      "inicio.subtitulo": "Supervisor control center",
      "inicio.disponible": "Available",
      "inicio.kpi.limpiezas": "Cleanings today",
      "inicio.kpi.incidencias": "Open issues",
      "inicio.kpi.empleados": "Active employees",
      "inicio.kpi.edificios": "Buildings",
      "inicio.admin": "Admin",
      "inicio.registros.t": "Records",
      "inicio.registros.d": "See cleaned areas, photos and times in real time",
      "inicio.empleados.t": "Employees",
      "inicio.empleados.d": "Add, activate or deactivate cleaning staff",
      "inicio.edificios.t": "Buildings & areas",
      "inicio.edificios.d": "Manage spaces and generate QR codes per area",
      "inicio.incidencias.t": "Issues",
      "inicio.incidencias.d": "Reports of missing supplies and problems in each building",
      "inicio.estadisticas.t": "Statistics",
      "inicio.estadisticas.d": "Compliance, most-attended areas and trends",
      "inicio.reportes.t": "Reports",
      "inicio.reportes.d": "Monthly PDF report to present to your client",
      "inicio.soporte.t": "Support",
      "inicio.soporte.d": "Contact and help using the platform",
      "inicio.administracion.t": "Administration",
      "inicio.administracion.d": "Subscription, team and company summary",

      "reg.titulo": "Cleaning records",
      "reg.tiempo_real": "Real time",
      "reg.actualizar": "Refresh",
      "reg.m_hoy": "Records today",
      "reg.m_foto": "With photo",
      "reg.m_total": "All-time total",
      "reg.edificio": "Building",
      "reg.todos_edificios": "All buildings",
      "reg.sin_datos": "No data yet",
      "reg.cargando": "Loading records...",
      "reg.vacio_edificio": "No records in this building yet.",
      "reg.vacio_todos": "No records yet. When an employee logs an area, it will appear here.",
      "reg.con_foto": "With photo",
      "reg.registrado": "Logged",
      "reg.hoy": "Today",
      "reg.ayer": "Yesterday",

      "inc.titulo": "Issues",
      "inc.subtitulo": "Missing supplies and reported problems",
      "inc.pendientes": "Pending",
      "inc.resueltas": "Resolved",
      "inc.total": "Total",
      "inc.f_pendientes": "Pending",
      "inc.f_resueltas": "Resolved",
      "inc.f_todas": "All",
      "inc.cargando": "Loading issues...",
      "inc.vacio_pend": "No pending issues. All good!",
      "inc.vacio_resueltas": "No resolved issues yet.",
      "inc.vacio_todas": "No issues.",
      "inc.tipo_insumo": "Missing supply",
      "inc.tipo_problema": "Problem",
      "inc.estado_resuelta": "Resolved",
      "inc.estado_pendiente": "Pending",
      "inc.btn_resolver": "Mark as resolved",
      "inc.btn_reabrir": "Reopen",
      "inc.error_actualizar": "Could not update: ",

      "est.titulo": "Statistics",
      "est.subtitulo": "Performance and trends by building",
      "est.cargando": "Loading statistics...",
      "est.sin_datos": "No data yet",
      "est.vacio": "No records yet. When employees log areas, their statistics will appear here grouped by building.",
      "est.de_edificio": "Statistics for this building",
      "est.m_total": "Total records",
      "est.m_hoy": "Today",
      "est.m_semana": "This week",
      "est.m_foto": "% with photo",
      "est.g_dias": "Activity last 7 days",
      "est.g_areas": "Most-attended areas",
      "est.g_emp": "Activity per employee",
      "est.otras": "Others",

      "sop.titulo": "Help center",
      "sop.subtitulo": "Frequently asked questions and support contact",
      "sop.buscar": "Type your question...",
      "sop.faq_label": "Frequently asked questions",
      "sop.sin_resultados": "We couldn't find an answer for that. Send us your question below and we'll help.",
      "sop.form_titulo": "Didn't find your answer?",
      "sop.form_sub": "Send us your question and we'll review it",
      "sop.form_ph": "Type your question here...",
      "sop.enviar": "Send question",
      "sop.escribe": "Type your question.",
      "sop.enviando": "Sending...",
      "sop.error": "Error sending: ",
      "sop.ok": "✓ Your question was sent. We'll reply soon.",

      "pan.sin_acceso": "This section is only for the company administrator.",
      "pan.volver": "← Back to home",
      "pan.titulo": "Admin panel",
      "pan.subtitulo": "Subscription, summary and your company team",
      "pan.sub_titulo": "Your subscription",
      "pan.sub_cargando": "Loading...",
      "pan.sub_error": "Could not load the subscription.",
      "pan.f_empresa": "Company",
      "pan.f_estado": "Status",
      "pan.f_inicio": "Trial start",
      "pan.f_fin": "Trial end",
      "pan.f_edificios": "Contracted buildings",
      "pan.f_precio": "Monthly price",
      "pan.est_activa": "Active",
      "pan.est_prueba": "Free trial",
      "pan.est_suspendida": "Suspended",
      "pan.resumen_titulo": "Your company summary",
      "pan.r_edificios": "Buildings",
      "pan.r_empleados": "Employees",
      "pan.r_registros": "Records this month",
      "pan.equipo_titulo": "Your supervisor team",
      "pan.equipo_cargando": "Loading...",
      "pan.equipo_vacio": "No supervisors registered.",
      "pan.nota": "To add or remove supervisors, contact technical support for now. Soon you'll be able to manage them directly from here.",
      "pan.rol_admin": "Administrator",
      "pan.rol_supervisor": "Supervisor",

      "emp.titulo": "Employees",
      "emp.subtitulo": "Manage cleaning staff and their PINs",
      "emp.ver_registros": "View records",
      "emp.agregar_titulo": "Add employee",
      "emp.nombre": "Full name",
      "emp.nombre_ph": "e.g. Ana Torres",
      "emp.pin": "PIN (4 digits)",
      "emp.pin_ph": "e.g. 4892",
      "emp.generar": "Generate",
      "emp.edificios": "Buildings where they work",
      "emp.buscar_edificio": "Search and add building...",
      "emp.btn_agregar": "Add employee",
      "emp.lista_titulo": "Employees",
      "emp.buscar": "Search by name or building...",
      "emp.f_todos": "All",
      "emp.f_activos": "Active",
      "emp.f_inactivos": "Inactive",
      "emp.cargando": "Loading...",
      "emp.editar_titulo": "Edit employee",
      "emp.cancelar": "Cancel",
      "emp.guardar": "Save changes",
      "emp.sin_edificios": "No buildings assigned",
      "emp.vacio": "No employees found.",
      "emp.pin_label": "PIN: ",
      "emp.vacio_inicial": "No employees yet. Add the first one above.",
      "emp.sin_coincidencias": "No matches.",
      "emp.sin_edificio_asignado": "No building assigned",
      "emp.todos_agregados": "You've already added all buildings.",

      "area.titulo": "Buildings & areas",
      "area.subtitulo": "Manage spaces and generate QR codes per area",
      "area.crear_edificio": "Create building",
      "area.crear_area": "Create area",
      "area.lista_titulo": "Buildings and their areas",
      "area.lista_sub": "Each building with its areas. Tap \"Generate QR code\" to download each area's QR.",
      "area.cargando": "Loading...",
      "area.m_edificio_titulo": "Create building",
      "area.m_editar_titulo": "Edit building",
      "area.f_nombre_ed": "Building name *",
      "area.f_direccion": "Address",
      "area.f_contacto": "Contact person",
      "area.f_telefono": "Phone",
      "area.f_email": "Email",
      "area.f_pisos": "Number of floors",
      "area.f_notas": "Notes",
      "area.guardar_ed": "Save building",
      "area.guardar_cambios": "Save changes",
      "area.cancelar": "Cancel",
      "area.m_area_titulo": "Create area",
      "area.f_nombre_area": "Area name *",
      "area.f_edificio": "Building *",
      "area.f_requiere_foto": "Requires photo when logging",
      "area.crear_area_btn": "Create area",
      "area.qr_imprimir": "Print card",
      "area.qr_cerrar": "Close",
      "area.req_nombre_ed": "The building name is required.",
      "area.guardando": "Saving...",
      "area.sin_areas": "No areas yet.",
      "area.areas_count": "area(s)",
      "area.generar_qr": "Generate QR code",
      "area.req_nombre_area": "Type the area name.",
      "area.area_sing": "area",
      "area.area_plu": "areas",
      "area.activa_sing": "active",
      "area.activa_plu": "active",
      "area.requiere_foto_txt": "Requires photo · ",
      "area.activa": "Active",
      "area.inactiva": "Inactive",
      "area.sin_areas_msg": "This building has no areas yet. Use \"Create area\" to add the first one.",
      "area.qr_title": "QR code for this area",

      "rep.titulo": "Reports",
      "rep.generar_titulo": "Generate report",
      "rep.generar_sub": "Create a PDF report to present to your client",
      "rep.edificio": "Building",
      "rep.tipo": "Report type",
      "rep.tipo_diario": "Daily (one day)",
      "rep.tipo_semanal": "Weekly (last 7 days)",
      "rep.tipo_mes_actual": "Monthly (this month)",
      "rep.tipo_mes_pasado": "Monthly (last month)",
      "rep.dia_informe": "Report day",
      "rep.btn_generar": "Generate PDF",
      "rep.preview_titulo": "Report preview",
      "rep.pv_areas": "Areas cleaned",
      "rep.pv_foto": "With photo",
      "rep.pv_dias": "Active days",
      "rep.pv_inc": "Issues",
      "rep.cargando_lista": "Loading...",
      "rep.sin_datos": "No data yet",
      "rep.generando": "Generating PDF...",
      "rep.listo": "✓ PDF generated and downloaded.",
      "rep.error": "Error generating: ",
      "rep.sel_edificio": "Select a building.",
      "pdf.sub_diario": "Daily cleaning report",
      "pdf.sub_semanal": "Weekly cleaning report",
      "pdf.sub_mensual": "Monthly cleaning report",
      "pdf.periodo": "Period: ",
      "pdf.generado": "Generated: ",
      "pdf.pie": "Report generated by CleanTrack",
      "pdf.t_areas_limpiadas": "Areas cleaned",
      "pdf.t_con_foto": "With photo",
      "pdf.t_empleados": "Employees",
      "pdf.t_incidencias": "Issues",
      "pdf.t_limpiezas": "Cleanings",
      "pdf.t_dias_trab": "Days worked",
      "pdf.t_areas_cub": "Areas covered",
      "pdf.t_limpiezas_real": "Cleanings done",
      "pdf.t_inc_resueltas": "Issues resolved",
      "pdf.s_detalle": "Cleaning detail",
      "pdf.s_inc_reportadas": "Reported issues",
      "pdf.s_act_dia": "Activity per day",
      "pdf.s_inc_semana": "Issues this week",
      "pdf.s_act_semana": "Activity per week",
      "pdf.s_areas_atendidas": "Most-attended areas",
      "pdf.s_inc_mes": "Issues this month",
      "pdf.vacio_limpiezas": "No cleanings were logged in this period.",
      "pdf.vacio_inc_periodo": "No issues were reported in this period.",
      "pdf.vacio_inc_semana": "No issues were reported this week.",
      "pdf.vacio_inc_mes": "No issues were reported this month.",
      "pdf.ultimos7": "last 7 days",
      "pdf.de": " ",
      "pdf.meses": "January,February,March,April,May,June,July,August,September,October,November,December",

      "epl.cargando_area": "Loading area...",
      "epl.label_pin": "Enter your PIN to log",
      "epl.verificando": "Checking...",
      "epl.borrar": "Delete",
      "epl.hola": "Hi",
      "epl.tomar_foto": "Take photo of the area",
      "epl.confirmar": "Confirm area cleaned",
      "epl.registrar_con_foto": "Log area with this photo",
      "epl.reportar_inc": "Report an issue",
      "epl.exito_titulo": "Area logged",
      "epl.exito_nota": "Scan the next area's code when you finish cleaning it.",
      "epl.inc_titulo": "Report issue",
      "epl.inc_insumo": "A supply is missing",
      "epl.inc_problema": "There's a problem",
      "epl.inc_desc_label": "Description",
      "epl.inc_desc_ph": "e.g. The soap dispenser is empty / The toilet is clogged",
      "epl.inc_agregar_foto": "Add photo (optional)",
      "epl.inc_cambiar_foto": "Change photo",
      "epl.inc_enviar": "Send report",
      "epl.cancelar": "Cancel",
      "epl.area_no_esp": "Area not specified",
      "epl.escanea_valido": "Scan a valid QR code",
      "epl.area_no_enc": "Area not found",
      "epl.verifica_qr": "Check the QR code",
      "epl.sin_conexion": "No connection to the database.",
      "epl.error_subir": "Error uploading photo: ",
      "epl.guardando": "Saving record...",
      "epl.no_guardar": "Could not save: ",
      "epl.error": "Error: ",
      "epl.inc_elige_tipo": "Choose the type: missing supply or problem.",
      "epl.inc_describe": "Describe the issue.",
      "epl.inc_subiendo": "Uploading photo...",
      "epl.inc_enviando": "Sending report...",
      "epl.inc_no_enviar": "Could not send: ",
      "epl.inc_ok": "✓ Report sent. Thank you!",
      "epl.pin_incorrecto": "Incorrect PIN. Try again.",
      "epl.sin_conexion_corta": "No connection",
      "epl.demasiados": "Too many attempts. Wait a moment.",
      "epl.error_verificar": "Verification error. Try again.",
      "epl.pin_no_valido": "Invalid PIN",

      "log.titulo": "Supervisor panel",
      "log.subtitulo": "Professional cleaning management",
      "log.email": "Email",
      "log.email_ph": "youremail@company.com",
      "log.password": "Password",
      "log.entrar": "Log in",
      "log.pie": "CleanTrack · Secure access",
      "log.falta": "Enter your email and password.",
      "log.sin_conexion": "No connection to the database.",
      "log.verificando": "Checking...",
      "log.incorrectos": "Incorrect email or password.",

      "land.titulo_pagina": "CleanTrack — Prove every cleaning your team delivers",
      "land.nav_how": "How it works",
      "land.nav_why": "Why CleanTrack",
      "land.nav_quote": "Get a quote",
      "land.nav_login": "Supervisor login",
      "land.hero_h1": "Prove the great cleaning<br>your team <span class=\"acento\">delivers</span>",
      "land.hero_sub": "The platform that turns every cleaning into evidence your clients can see.",
      "land.hero_cta1": "Contact us for a quote",
      "land.hero_cta2": "See how it works",
      "land.prob_eyebrow": "⚠ The problem",
      "land.prob_h2": "Doing great work isn't enough.<br>You have to <span class=\"rojo\">prove it</span>.",
      "land.prob_intro": "Cleaning companies don't lose contracts for working badly — they lose them for having no way to prove the work was done.",
      "land.prob1_h": "\"Are you sure it was cleaned today?\"",
      "land.prob1_p": "The property manager has doubts, and without proof, your word isn't always enough to reassure them.",
      "land.prob2_h": "Complaints with no backup",
      "land.prob2_p": "When a claim comes in, you have no record of what was done, when, or who did it.",
      "land.prob3_h": "Contracts that don't renew",
      "land.prob3_p": "Without evidence of the value you deliver, it's hard to justify continuing the service.",
      "land.prob_banner": "What if every cleaning was logged <span class=\"hl\">automatically, with the exact time</span> — and you could require a photo in the areas you choose, like the <span class=\"hl\">lobby</span> or the <span class=\"hl\">lounge</span>?",
      "land.sol_eyebrow": "✓ The solution",
      "land.sol_h2": "Everything gets logged.<br>You see it <span class=\"verde\">in real time</span>.",
      "land.sol_intro": "Every cleaned area and every incident appears instantly on your dashboard and your supervisors', with all the detail you need.",
      "land.sol1_h": "Activity at a glance",
      "land.sol1_p": "The moment an employee logs an area, it appears on your dashboard with who cleaned it, what time, and where — with photo evidence wherever you decide.",
      "land.sol2_h": "Incidents with full detail",
      "land.sol2_p": "If a supply runs out or something breaks, your team reports it on the spot. You get the alert with the area, the description and a photo, so you can fix it fast.",
      "land.sol3_h": "Reports for your client",
      "land.sol3_p": "Generate a report for any day, week or month and send it to the property manager. Professional, backed by evidence, ready in seconds.",
      "land.sol4_h": "Photo where you decide",
      "land.sol4_p": "Require photo evidence only in the critical areas — without slowing your team down everywhere else.",
      "land.how_eyebrow": "⚡ How it works",
      "land.how_h2": "Four steps. <span class=\"verde\">Zero hassle</span>.",
      "land.how_intro": "So simple your team uses it from day one — no training needed.",
      "land.how1_h": "Scan the area QR",
      "land.how1_p": "Each area has its own QR code. The employee arrives and scans it with their phone. No app to install.",
      "land.how2_h": "Enter their PIN",
      "land.how2_p": "Each employee has a personal 4-digit PIN. They enter it and the system knows who did the cleaning — no complicated logins.",
      "land.how3_h": "Log the cleaning",
      "land.how3_p": "The record is saved with the exact time and the employee's name. You can require a photo in the areas you choose.",
      "land.how4_h": "Supervise in real time",
      "land.how4_p": "You and your supervisors see all activity from the dashboard, instantly. No calls, no waiting for reports.",
      "land.video_h": "See it in action",
      "land.video_sub": "A quick look at how CleanTrack works, from scanning the QR to your live dashboard.",
      "land.video_fallback": "Your browser does not support the video tag.",
      "land.why_eyebrow": "✓ Why CleanTrack",
      "land.why_h2": "The difference is in the <span class=\"verde\">simplicity</span>.",
      "land.why_intro": "Other platforms are complex, expensive and English-only. CleanTrack does what matters, well and easily.",
      "land.tab_th_ct": "CleanTrack",
      "land.tab_th_otros": "Others",
      "land.tab_r1": "Ease of use",
      "land.tab_r1_ct": "No training",
      "land.tab_r1_o": "Learning curve",
      "land.tab_r2": "Language",
      "land.tab_r2_ct": "Spanish & English",
      "land.tab_r2_o": "English only",
      "land.tab_r3": "Photo evidence",
      "land.tab_r3_ct": "Configurable per area",
      "land.tab_r3_o": "Limited or extra",
      "land.tab_r4": "Client reports",
      "land.tab_r4_ct": "Professional",
      "land.tab_r4_o": "Basic",
      "land.tab_r5": "Monthly price",
      "land.tab_r5_ct": "Accessible",
      "land.tab_r5_o": "High",
      "land.cta_h2": "Start proving<br>your value <span class=\"acento\">today</span>",
      "land.cta_sub": "Your first 30 days are free. We help you set everything up — no cost, no commitment.",
      "land.cta_btn": "Contact us for a quote",
      "land.foot_frase": "Every cleaning, verified.",
      "land.foot_login": "Supervisor login"
    }
  };

  function detectar() {
    try {
      var guardado = localStorage.getItem("ct_idioma");
      if (guardado === "es" || guardado === "en") return guardado;
    } catch (e) {}
    var nav = (navigator.language || navigator.userLanguage || "es").toLowerCase();
    return nav.indexOf("en") === 0 ? "en" : "es";
  }

  var lang = detectar();
  var callbacks = [];

  // Traduce una clave al idioma actual (con respaldo a español y a la propia clave)
  function t(clave) {
    var d = DICT[lang] || DICT.es;
    if (d[clave] != null) return d[clave];
    if (DICT.es[clave] != null) return DICT.es[clave];
    return clave;
  }

  // Rellena en el HTML todos los elementos marcados:
  //   data-i18n="clave"        -> textContent
  //   data-i18n-ph="clave"     -> placeholder
  //   data-i18n-html="clave"   -> innerHTML (solo para textos de marketing controlados por nosotros,
  //                               nunca para datos de usuario; permite <br> y <span> en titulares)
  function aplicar(root) {
    root = root || document;
    root.querySelectorAll("[data-i18n]").forEach(function (el) {
      el.textContent = t(el.getAttribute("data-i18n"));
    });
    root.querySelectorAll("[data-i18n-ph]").forEach(function (el) {
      el.setAttribute("placeholder", t(el.getAttribute("data-i18n-ph")));
    });
    root.querySelectorAll("[data-i18n-html]").forEach(function (el) {
      el.innerHTML = t(el.getAttribute("data-i18n-html"));
    });
    document.documentElement.setAttribute("lang", lang);
    actualizarBotones();
  }

  function actualizarBotones() {
    // El botón muestra el idioma al que se cambiaría
    document.querySelectorAll("[data-i18n-toggle]").forEach(function (b) {
      b.textContent = (lang === "es") ? "EN" : "ES";
    });
  }

  function set(nuevo) {
    if (nuevo !== "es" && nuevo !== "en") return;
    lang = nuevo;
    try { localStorage.setItem("ct_idioma", lang); } catch (e) {}
    aplicar();
    callbacks.forEach(function (fn) { try { fn(lang); } catch (e) {} });
  }

  function toggle() { set(lang === "es" ? "en" : "es"); }

  // Permite que cada pantalla re-dibuje su contenido dinámico al cambiar idioma
  function onChange(fn) { if (typeof fn === "function") callbacks.push(fn); }

  function idioma() { return lang; }

  // Preguntas frecuentes en ambos idiomas (las usa soporte.html)
  var FAQ = {
    es: [
      { p: "¿Cómo registro la limpieza de un área?", r: "El empleado escanea el código QR pegado en el área con la cámara de su celular. Se abre la app, ingresa su PIN de 4 dígitos, toma una foto si se le solicita, y confirma. El registro queda guardado con la hora exacta.", clave: "registrar limpieza area empleado escanear qr pin foto" },
      { p: "¿Cómo agrego un nuevo empleado?", r: "Entra a 'Empleados' desde el inicio. Escribe el nombre y un PIN de 4 dígitos, y toca 'Agregar empleado'. El empleado ya podrá usar ese PIN para registrar áreas.", clave: "agregar nuevo empleado pin nombre crear personal" },
      { p: "¿Cómo desactivo a un empleado que ya no trabaja?", r: "En 'Empleados', busca a la persona y toca su interruptor para ponerlo en 'Inactivo'. Su PIN dejará de funcionar de inmediato, pero su historial de registros se conserva.", clave: "desactivar empleado despedir quitar inactivo pin dejar trabajar" },
      { p: "¿Cómo creo un edificio?", r: "Entra a 'Edificios y áreas' y toca 'Crear edificio'. Llena el nombre y los datos que quieras (dirección, contacto, etc.) y guarda. Luego podrás crear áreas dentro de ese edificio.", clave: "crear edificio nuevo direccion contacto agregar" },
      { p: "¿Cómo creo un área?", r: "En 'Edificios y áreas', toca 'Crear área'. Escribe el nombre del área, elige el edificio de la lista, marca si requiere foto, y crea. El área aparecerá agrupada bajo su edificio.", clave: "crear area nueva edificio bano lobby piso requiere foto" },
      { p: "¿Cómo genero el código QR de un área?", r: "En 'Edificios y áreas', abre el edificio, busca el área y toca 'Generar código QR'. Aparecerá el QR, que puedes descargar para imprimir y pegar en el área. Cada área tiene su propio QR único.", clave: "generar codigo qr area imprimir descargar pegar" },
      { p: "¿Qué hago si un código QR se daña o se pierde?", r: "Simplemente vuelve a 'Edificios y áreas', abre el área, y genera su QR de nuevo. El QR será el mismo que el anterior, así que el historial no se pierde. Imprímelo y reemplaza el dañado.", clave: "qr danado perdido roto reimprimir reemplazar generar nuevo" },
      { p: "¿Cómo veo los registros de limpieza?", r: "Entra a 'Registros' desde el inicio. Verás todas las áreas limpiadas, con el nombre del empleado, la hora, y la foto si la hubo. Se actualiza automáticamente.", clave: "ver registros limpieza dashboard panel historial fotos" },
      { p: "¿Cómo descargo el informe mensual en PDF?", r: "Entra a 'Reportes', elige el edificio y el período (este mes, mes pasado o últimos 7 días), y toca 'Generar PDF'. Se descargará un informe profesional que puedes imprimir o enviar a tu cliente.", clave: "descargar informe reporte pdf mensual cliente edificio periodo" },
      { p: "¿Cómo veo las estadísticas?", r: "Entra a 'Estadísticas' y elige un edificio en el menú de arriba. Verás los números, la actividad de los últimos 7 días, y los rankings de áreas y empleados de ese edificio.", clave: "estadisticas datos graficas numeros rendimiento edificio" }
    ],
    en: [
      { p: "How do I log the cleaning of an area?", r: "The employee scans the QR code posted in the area with their phone camera. The app opens, they enter their 4-digit PIN, take a photo if requested, and confirm. The record is saved with the exact time.", clave: "log cleaning area employee scan qr pin photo registrar" },
      { p: "How do I add a new employee?", r: "Go to 'Employees' from the home screen. Type the name and a 4-digit PIN, and tap 'Add employee'. The employee can then use that PIN to log areas.", clave: "add new employee pin name create staff agregar" },
      { p: "How do I deactivate an employee who no longer works here?", r: "In 'Employees', find the person and tap their switch to set them 'Inactive'. Their PIN stops working immediately, but their record history is kept.", clave: "deactivate employee remove inactive pin desactivar" },
      { p: "How do I create a building?", r: "Go to 'Buildings & areas' and tap 'Create building'. Fill in the name and any details you want (address, contact, etc.) and save. Then you can create areas inside that building.", clave: "create building new address contact add crear edificio" },
      { p: "How do I create an area?", r: "In 'Buildings & areas', tap 'Create area'. Type the area name, pick the building from the list, mark whether it requires a photo, and create. The area appears grouped under its building.", clave: "create area new building bathroom lobby floor requires photo crear" },
      { p: "How do I generate an area's QR code?", r: "In 'Buildings & areas', open the building, find the area and tap 'Generate QR code'. The QR appears, and you can download it to print and post in the area. Each area has its own unique QR.", clave: "generate qr code area print download post crear" },
      { p: "What do I do if a QR code is damaged or lost?", r: "Just go back to 'Buildings & areas', open the area, and generate its QR again. The QR is the same as before, so history isn't lost. Print it and replace the damaged one.", clave: "qr damaged lost broken reprint replace generate new danado" },
      { p: "How do I view the cleaning records?", r: "Go to 'Records' from the home screen. You'll see all cleaned areas, with the employee name, time, and photo if any. It updates automatically.", clave: "view records cleaning dashboard history photos registros" },
      { p: "How do I download the monthly PDF report?", r: "Go to 'Reports', choose the building and the period (this month, last month, or last 7 days), and tap 'Generate PDF'. A professional report downloads that you can print or send to your client.", clave: "download report pdf monthly client building period reporte" },
      { p: "How do I view the statistics?", r: "Go to 'Statistics' and choose a building in the top menu. You'll see the numbers, the last 7 days of activity, and the area and employee rankings for that building.", clave: "statistics data charts numbers performance building estadisticas" }
    ]
  };

  window.I18N = {
    t: t,
    aplicar: aplicar,
    set: set,
    toggle: toggle,
    onChange: onChange,
    idioma: idioma,
    actualizarBotones: actualizarBotones,
    faq: function () { return FAQ[lang] || FAQ.es; }
  };
})();
